# Generated by Django 5.0.3 on 2024-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('clothing_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('now_at', models.CharField(max_length=20)),
                ('rfid_uid', models.CharField(db_column='RFID_uid', max_length=15)),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('washed_at', models.DateTimeField()),
                ('location_modified_at', models.DateTimeField()),
                ('polluted', models.IntegerField()),
                ('worn_count', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clothing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingDetail',
            fields=[
                ('clothing_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clothing_img_path', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'clothing_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingSeason',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
            ],
            options={
                'db_table': 'clothing_season',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingStyle',
            fields=[
                ('style_connection_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clothing_style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClothingTexture',
            fields=[
                ('texture_connection_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'clothing_texture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.AutoField(primary_key=True, serialize=False)),
                ('washer_id', models.IntegerField()),
                ('air_dresser_id', models.IntegerField()),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PastOutfit',
            fields=[
                ('past_outfit_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'past_outfit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecommendedOutfit',
            fields=[
                ('recommended_outfit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'recommended_outfit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=20)),
                ('schedule_category', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('location_key', models.IntegerField()),
                ('outfit_image_path', models.CharField(max_length=200)),
                ('schedule_disabled', models.IntegerField()),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiDo',
            fields=[
                ('si_do_id', models.AutoField(primary_key=True, serialize=False)),
                ('si_do_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'si_do',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiGunGu',
            fields=[
                ('si_gun_gu_id', models.AutoField(primary_key=True, serialize=False)),
                ('si_gun_gu_name', models.CharField(max_length=20)),
                ('location_key', models.IntegerField()),
            ],
            options={
                'db_table': 'si_gun_gu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('style_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'style',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('texture_id', models.AutoField(primary_key=True, serialize=False)),
                ('texture_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'texture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('profile_img_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('fcm_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserClothing',
            fields=[
                ('clothing_connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('clothing_name', models.CharField(max_length=20)),
                ('accrue_worn_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_clothing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_key', models.IntegerField()),
                ('icon', models.IntegerField()),
                ('lowest_temperature', models.IntegerField()),
                ('highest_temperature', models.IntegerField()),
                ('highest_real_feeling_temperature', models.IntegerField()),
                ('lowest_real_feeling_temperature', models.IntegerField()),
                ('precipitation', models.IntegerField()),
                ('snow_cover', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('solar_irradiance', models.IntegerField(db_column='solar_Irradiance')),
                ('uv', models.IntegerField()),
                ('uv_message', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'weather',
                'managed': False,
            },
        ),
    ]
